<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-9B42UR3" failures="1" tests="10" name="Test" time="23.512" errors="0" timestamp="2025-08-10T09:54:20 IST">
  <testcase classname="api.test.DDTests" name="testPostuser" time="5.366"/>
  <testcase classname="api.test.DDTests" name="testPostuser" time="1.142"/>
  <testcase classname="api.test.DDTests" name="testPostuser" time="1.218"/>
  <testcase classname="api.test.DDTests" name="testPostuser" time="1.244"/>
  <testcase classname="api.test.DDTests" name="testPostuser" time="1.184"/>
  <testcase classname="api.test.DDTests" name="testDeleteuser" time="1.296"/>
  <testcase classname="api.test.DDTests" name="testDeleteuser" time="1.212"/>
  <testcase classname="api.test.DDTests" name="testDeleteuser" time="1.168"/>
  <testcase classname="api.test.DDTests" name="testDeleteuser" time="1.158"/>
  <testcase classname="api.test.DDTests" name="testDeleteuser" time="1.203">
    <failure type="java.lang.AssertionError" message="Validatating response code :Uname016 expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: Validatating response code :Uname016 expected [200] but found [404]
at api.test.DDTests.testDeleteuser(DDTests.java:109)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteuser -->
</testsuite> <!-- Test -->
